"""
    This module contains the views function of the flask code
    where the image is loaded from the website and the relevent
    html code is generated
"""

import logging
import io
from PIL import Image
from flask import Flask, render_template, request, redirect, url_for
from converters import Converter
from model_loader import ModelConverter


logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, filemode='w', filename='logger.log')

app = Flask(__name__)

def get_model():
    """
        This function is used to get the model
    """
    return ModelConverter()

def get_html_from_converter():
    """
        This function is used to generate the html from the
        coordinate location of the html element get from the
        model
    """
    converter = Converter()
    return converter.get_html()


@app.route('/', methods=['GET', 'POST'])
def index():
    """
        This function is used to get the image as POST method
        and display the html code output, by default this function
        renders the root page of the website
    """
    model = get_model()
    result = None
    if request.method == 'POST':
        if img_file := request.files['image']:
            img = Image.open(io.BytesIO(img_file.read()))
            model.model_to_coordinates(img)
            result = get_html_from_converter()
            return redirect(url_for('generate_html', result=result))
    return render_template('index.html')


@app.route('/output')
def generate_html():
    """
        This function is used to display the html code generated from
        the coordinates location of the html elements get from the model
    """
    result = get_html_from_converter()
    return render_template('showhtml.html', result=result)


@app.route('/preview')
def preview_html():
    """
        This function is used to display the html code generated by the model
        in safe mode
    """
    result = get_html_from_converter()
    return render_template('preview.html', result=result)

@app.route('/aboutus')
def about_us():
    return render_template('aboutus.html')

if __name__ == "__main__":
    app.run(debug=True)

